on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Build and Test

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get install -y cmake libgtest-dev libgmock-dev googletest

      - name: Cache Dependency Builds
        id: cache-deps-build
        uses: actions/cache@v3
        with:
          path: build-deps
          key: ${{ runner.os }}-1

      - name: Init build dir
        if: steps.cache-deps-build.outputs.cache-hit != 'true'
        run: mkdir build-deps

      - name: Build googletest
        if: steps.cache-deps-build.outputs.cache-hit != 'true'
        run: |
          mkdir build-deps/googletest
          cd build-deps/googletest
          cmake /usr/src/googletest
          cmake --build .
          cmake --install . --prefix ../../dist

      - name: Fetch Arrow
        if: steps.cache-deps-build.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: apache/arrow
          ref: apache-arrow-8.0.0
          path: build-deps/arrow
          fetch-depth: 0

      - name: Build Arrow
        if: steps.cache-deps-build.outputs.cache-hit != 'true'
        run: |
          mkdir build-deps/arrow-build
          cd build-deps/arrow-build
          cmake ../arrow/cpp -DGTest_DIR=../../dist/lib/cmake/GTest -DARROW_JSON=ON -DARROW_TESTING=ON -DBoost_SOURCE=BUNDLED
          cmake --build .
          cmake --install . --prefix ../../dist

      - name: Install Dependencies
        run: |
          cd build-deps/arrow-build
          cmake --install . --prefix ../../dist
          cd ../googletest
          cmake --install . --prefix ../../dist

      - name: Build arrowc
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug -DGTest_DIR=../../dist/lib/cmake/GTest -DArrow_DIR=`pwd`/../dist/lib/cmake/arrow -DArrowTesting_DIR=`pwd`/../dist/lib/cmake/arrow -DARROWC_CODE_COVERAGE=ON -DARROWC_BUILD_TESTS=ON
          cmake --build .

      - name: Run tests
        run: |
          cd build
          ctest -T test --output-on-failure .

      - name: Calculate coverage
        run: |
          mkdir build/cov
          cd build/cov
          gcov -abcfu `find ../CMakeFiles/arrowc.dir/ -name "*.gcno"`

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          directory: build/cov
